USE supply_chain_system;

-- Produtos semiacabados (MASSA/RECHEIO) gerados automaticamente a partir das fichas dos salgados
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - CROQUETE CARNE SECA 20 GRS', 'Semiacabado RECHEIO para CROQUETE CARNE SECA 20 GRS', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - CROQUETE CARNE SECA 20 GRS');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - BOLINHA DE QUEIJO 20 GRS', 'Semiacabado RECHEIO para BOLINHA DE QUEIJO 20 GRS', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - BOLINHA DE QUEIJO 20 GRS');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - ENROLADINHO PRES/QUEIJO 20GRS', 'Semiacabado RECHEIO para ENROLADINHO PRES/QUEIJO 20GRS', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - ENROLADINHO PRES/QUEIJO 20GRS');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - ENROLADINHO SALSICHA 20 GRS', 'Semiacabado RECHEIO para ENROLADINHO SALSICHA 20 GRS', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - ENROLADINHO SALSICHA 20 GRS');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'MASSA - BOLINHO DE CARNE 20 GRS', 'Semiacabado MASSA para BOLINHO DE CARNE 20 GRS', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'MASSA - BOLINHO DE CARNE 20 GRS');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - MINI CHURROS', 'Semiacabado RECHEIO para MINI CHURROS', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - MINI CHURROS');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - COXINHA MAND FRANGO 70 grs', 'Semiacabado RECHEIO para COXINHA MAND FRANGO 70 grs', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - COXINHA MAND FRANGO 70 grs');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - RISOLES TRIGO FRANGO 70 grs', 'Semiacabado RECHEIO para RISOLES TRIGO FRANGO 70 grs', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - RISOLES TRIGO FRANGO 70 grs');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - ENROLADINHO PRES/QUEIJO 70 GR', 'Semiacabado RECHEIO para ENROLADINHO PRES/QUEIJO 70 GR', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - ENROLADINHO PRES/QUEIJO 70 GR');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - QUIBE CARNE 70 GR', 'Semiacabado RECHEIO para QUIBE CARNE 70 GR', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - QUIBE CARNE 70 GR');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - QUIBE CARNE 130 GR', 'Semiacabado RECHEIO para QUIBE CARNE 130 GR', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - QUIBE CARNE 130 GR');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - QUIBE PROVOLONE 130 GR', 'Semiacabado RECHEIO para QUIBE PROVOLONE 130 GR', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - QUIBE PROVOLONE 130 GR');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - PASTEL DE CARNE', 'Semiacabado RECHEIO para PASTEL DE CARNE', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - PASTEL DE CARNE');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - TROUXINHA FRANGO C/ REQUEIJÃO', 'Semiacabado RECHEIO para TROUXINHA FRANGO C/ REQUEIJÃO', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - TROUXINHA FRANGO C/ REQUEIJÃO');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - PÃO DE BATATA REQUEIJÃO', 'Semiacabado RECHEIO para PÃO DE BATATA REQUEIJÃO', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - PÃO DE BATATA REQUEIJÃO');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - PÃO DE BATATA CARNE SECA REQUEIJÃO', 'Semiacabado RECHEIO para PÃO DE BATATA CARNE SECA REQUEIJÃO', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - PÃO DE BATATA CARNE SECA REQUEIJÃO');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - PÃO DE BATATA FRANGO/REQUEIJÃO', 'Semiacabado RECHEIO para PÃO DE BATATA FRANGO/REQUEIJÃO', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - PÃO DE BATATA FRANGO/REQUEIJÃO');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - COXINHA CARNE 140 grs', 'Semiacabado RECHEIO para COXINHA CARNE 140 grs', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - COXINHA CARNE 140 grs');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - COXINHA FRANGO 140 grs', 'Semiacabado RECHEIO para COXINHA FRANGO 140 grs', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - COXINHA FRANGO 140 grs');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - COXINHOCA CARNE SECA 130 grs', 'Semiacabado RECHEIO para COXINHOCA CARNE SECA 130 grs', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - COXINHOCA CARNE SECA 130 grs');
INSERT INTO products (internal_code, name, description, barcode, unit_measure, category_id, price, cost_price, margin, max_discount, active, category)
SELECT NULL, 'RECHEIO - COXINHOCA FRANGO /REQ 190 grs', 'Semiacabado RECHEIO para COXINHOCA FRANGO /REQ 190 grs', '', 'KG', NULL, 0.00, 0.00, 0.00, 0.00, 1, 'Semiacabado (Massa/Recheio/Caldo)' WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'RECHEIO - COXINHOCA FRANGO /REQ 190 grs');

-- Templates de producao para produtos salgados e semiacabados
INSERT INTO produto_templates_producao (
    produto_id, versao, nome_template, custo_total_base,
    tempo_producao_horas, ativo, observacoes, created_by
) VALUES
    ((SELECT id FROM products WHERE name = 'COXINHA CARNE MAND 20 grs' LIMIT 1), 1, 'Receita padrao - COXINHA CARNE MAND 20 grs', 0.00, NULL, 1, 'Rendimento: 1781.25 UNDS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'COXINHA FRANGO MAND 20 grs' LIMIT 1), 1, 'Receita padrao - COXINHA FRANGO MAND 20 grs', 0.00, NULL, 1, 'Rendimento: 1781.25 UNDS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'CROQUETE CARNE SECA 20 GRS' LIMIT 1), 1, 'Receita padrao - CROQUETE CARNE SECA 20 GRS', 0.00, NULL, 1, 'Rendimento: 1781.25 UNDS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'BOLINHA DE QUEIJO 20 GRS' LIMIT 1), 1, 'Receita padrao - BOLINHA DE QUEIJO 20 GRS', 0.00, NULL, 1, 'Rendimento: 1562.5 UNDS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'ENROLADINHO PRES/QUEIJO 20GRS' LIMIT 1), 1, 'Receita padrao - ENROLADINHO PRES/QUEIJO 20GRS', 0.00, NULL, 1, 'Rendimento: 1562.5 UNDS | Equivalente a: 29 PCTS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'ENROLADINHO SALSICHA 20 GRS' LIMIT 1), 1, 'Receita padrao - ENROLADINHO SALSICHA 20 GRS', 0.00, NULL, 1, 'Rendimento: 1857.142857142857 UNDS | Equivalente a: 31 PCTS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'QUIBE CARNE 20 GR' LIMIT 1), 1, 'Receita padrao - QUIBE CARNE 20 GR', 0.00, NULL, 1, 'Rendimento: 1350 UNDS | Equivalente a: 23 PCTS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'BOLINHO DE CARNE 20 GRS' LIMIT 1), 1, 'Receita padrao - BOLINHO DE CARNE 20 GRS', 0.00, NULL, 1, 'Rendimento: 1566.66 UNDS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'MINI CHURROS' LIMIT 1), 1, 'Receita padrao - MINI CHURROS', 0.00, NULL, 1, 'Rendimento: 1500 UNDS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'COXINHA MAND FRANGO 70 grs' LIMIT 1), 1, 'Receita padrao - COXINHA MAND FRANGO 70 grs', 0.00, NULL, 1, 'Rendimento: 500 UNDS | Equivalente a: 26 PCTS | Planilha: 70g', NULL),
    ((SELECT id FROM products WHERE name = 'RISOLES TRIGO FRANGO 70 grs' LIMIT 1), 1, 'Receita padrao - RISOLES TRIGO FRANGO 70 grs', 0.00, NULL, 1, 'Rendimento: 438.59649122807014 UNDS | Equivalente a: 22 PCTS | Planilha: 70g', NULL),
    ((SELECT id FROM products WHERE name = 'ENROLADINHO PRES/QUEIJO 70 GR' LIMIT 1), 1, 'Receita padrao - ENROLADINHO PRES/QUEIJO 70 GR', 0.00, NULL, 1, 'Rendimento: 438.59649122807014 UNDS | Equivalente a: 22 PCTS | Planilha: 70g', NULL),
    ((SELECT id FROM products WHERE name = 'QUIBE CARNE 70 GR' LIMIT 1), 1, 'Receita padrao - QUIBE CARNE 70 GR', 0.00, NULL, 1, 'Rendimento: 397.0588235294117 UNDS | Equivalente a: 21.5 PCTS | Planilha: 70g', NULL),
    ((SELECT id FROM products WHERE name = 'QUIBE CARNE 130 GR' LIMIT 1), 1, 'Receita padrao - QUIBE CARNE 130 GR', 0.00, NULL, 1, 'Rendimento: 241.07142857142856 UNDS | Equivalente a: 24 PCTS | Planilha: Quibe', NULL),
    ((SELECT id FROM products WHERE name = 'QUIBE PROVOLONE 130 GR' LIMIT 1), 1, 'Receita padrao - QUIBE PROVOLONE 130 GR', 0.00, NULL, 1, 'Rendimento: 241.07142857142856 UNDS | Equivalente a: 25 PCTS | Planilha: Quibe', NULL),
    ((SELECT id FROM products WHERE name = 'PASTEL DE CARNE' LIMIT 1), 1, 'Receita padrao - PASTEL DE CARNE', 0.00, NULL, 1, 'Rendimento: 117.6470588235294 UNDS | Equivalente a: 11.76470588235294  | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'TROUXINHA FRANGO C/ REQUEIJÃO' LIMIT 1), 1, 'Receita padrao - TROUXINHA FRANGO C/ REQUEIJÃO', 0.00, NULL, 1, 'Rendimento: 88.21052631578948 UNDS | Equivalente a: 8.821052631578947  | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'PÃO DE BATATA REQUEIJÃO' LIMIT 1), 1, 'Receita padrao - PÃO DE BATATA REQUEIJÃO', 0.00, NULL, 1, 'Rendimento: 181.25 UNDS | Equivalente a: 18.125  | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'PÃO DE BATATA CARNE SECA REQUEIJÃO' LIMIT 1), 1, 'Receita padrao - PÃO DE BATATA CARNE SECA REQUEIJÃO', 0.00, NULL, 1, 'Rendimento: 181.25 UNDS | Equivalente a: 18.125  | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'PÃO DE BATATA FRANGO/REQUEIJÃO' LIMIT 1), 1, 'Receita padrao - PÃO DE BATATA FRANGO/REQUEIJÃO', 0.00, NULL, 1, 'Rendimento: 181.25 UNDS | Equivalente a: 18.125  | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'COXINHA CARNE 140 grs' LIMIT 1), 1, 'Receita padrao - COXINHA CARNE 140 grs', 0.00, NULL, 1, 'Rendimento: 252.21238938053096 UNDS | Planilha: Coxinha', NULL),
    ((SELECT id FROM products WHERE name = 'COXINHA FRANGO 140 grs' LIMIT 1), 1, 'Receita padrao - COXINHA FRANGO 140 grs', 0.00, NULL, 1, 'Rendimento: 252.21238938053096 UNDS | Planilha: Coxinha', NULL),
    ((SELECT id FROM products WHERE name = 'COXINHOCA CARNE SECA 130 grs' LIMIT 1), 1, 'Receita padrao - COXINHOCA CARNE SECA 130 grs', 0.00, NULL, 1, 'Rendimento: 279.4117647058824 UNDS | Planilha: Coxinha', NULL),
    ((SELECT id FROM products WHERE name = 'COXINHOCA FRANGO /REQ 190 grs' LIMIT 1), 1, 'Receita padrao - COXINHOCA FRANGO /REQ 190 grs', 0.00, NULL, 1, 'Rendimento: 203.57142857142856 UNDS | Planilha: Coxinha', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - CROQUETE CARNE SECA 20 GRS' LIMIT 1), 1, 'Recheio para CROQUETE CARNE SECA 20 GRS', 0.00, NULL, 1, 'Semiacabado recheio derivado de CROQUETE CARNE SECA 20 GRS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - BOLINHA DE QUEIJO 20 GRS' LIMIT 1), 1, 'Recheio para BOLINHA DE QUEIJO 20 GRS', 0.00, NULL, 1, 'Semiacabado recheio derivado de BOLINHA DE QUEIJO 20 GRS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - ENROLADINHO PRES/QUEIJO 20GRS' LIMIT 1), 1, 'Recheio para ENROLADINHO PRES/QUEIJO 20GRS', 0.00, NULL, 1, 'Semiacabado recheio derivado de ENROLADINHO PRES/QUEIJO 20GRS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - ENROLADINHO SALSICHA 20 GRS' LIMIT 1), 1, 'Recheio para ENROLADINHO SALSICHA 20 GRS', 0.00, NULL, 1, 'Semiacabado recheio derivado de ENROLADINHO SALSICHA 20 GRS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'MASSA - BOLINHO DE CARNE 20 GRS' LIMIT 1), 1, 'Massa para BOLINHO DE CARNE 20 GRS', 0.00, NULL, 1, 'Semiacabado massa derivado de BOLINHO DE CARNE 20 GRS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - MINI CHURROS' LIMIT 1), 1, 'Recheio para MINI CHURROS', 0.00, NULL, 1, 'Semiacabado recheio derivado de MINI CHURROS | Planilha: 20g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - COXINHA MAND FRANGO 70 grs' LIMIT 1), 1, 'Recheio para COXINHA MAND FRANGO 70 grs', 0.00, NULL, 1, 'Semiacabado recheio derivado de COXINHA MAND FRANGO 70 grs | Planilha: 70g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - RISOLES TRIGO FRANGO 70 grs' LIMIT 1), 1, 'Recheio para RISOLES TRIGO FRANGO 70 grs', 0.00, NULL, 1, 'Semiacabado recheio derivado de RISOLES TRIGO FRANGO 70 grs | Planilha: 70g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - ENROLADINHO PRES/QUEIJO 70 GR' LIMIT 1), 1, 'Recheio para ENROLADINHO PRES/QUEIJO 70 GR', 0.00, NULL, 1, 'Semiacabado recheio derivado de ENROLADINHO PRES/QUEIJO 70 GR | Planilha: 70g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - QUIBE CARNE 70 GR' LIMIT 1), 1, 'Recheio para QUIBE CARNE 70 GR', 0.00, NULL, 1, 'Semiacabado recheio derivado de QUIBE CARNE 70 GR | Planilha: 70g', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - QUIBE CARNE 130 GR' LIMIT 1), 1, 'Recheio para QUIBE CARNE 130 GR', 0.00, NULL, 1, 'Semiacabado recheio derivado de QUIBE CARNE 130 GR | Planilha: Quibe', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - QUIBE PROVOLONE 130 GR' LIMIT 1), 1, 'Recheio para QUIBE PROVOLONE 130 GR', 0.00, NULL, 1, 'Semiacabado recheio derivado de QUIBE PROVOLONE 130 GR | Planilha: Quibe', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - PASTEL DE CARNE' LIMIT 1), 1, 'Recheio para PASTEL DE CARNE', 0.00, NULL, 1, 'Semiacabado recheio derivado de PASTEL DE CARNE | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - TROUXINHA FRANGO C/ REQUEIJÃO' LIMIT 1), 1, 'Recheio para TROUXINHA FRANGO C/ REQUEIJÃO', 0.00, NULL, 1, 'Semiacabado recheio derivado de TROUXINHA FRANGO C/ REQUEIJÃO | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - PÃO DE BATATA REQUEIJÃO' LIMIT 1), 1, 'Recheio para PÃO DE BATATA REQUEIJÃO', 0.00, NULL, 1, 'Semiacabado recheio derivado de PÃO DE BATATA REQUEIJÃO | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - PÃO DE BATATA CARNE SECA REQUEIJÃO' LIMIT 1), 1, 'Recheio para PÃO DE BATATA CARNE SECA REQUEIJÃO', 0.00, NULL, 1, 'Semiacabado recheio derivado de PÃO DE BATATA CARNE SECA REQUEIJÃO | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - PÃO DE BATATA FRANGO/REQUEIJÃO' LIMIT 1), 1, 'Recheio para PÃO DE BATATA FRANGO/REQUEIJÃO', 0.00, NULL, 1, 'Semiacabado recheio derivado de PÃO DE BATATA FRANGO/REQUEIJÃO | Planilha: Pastel', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - COXINHA CARNE 140 grs' LIMIT 1), 1, 'Recheio para COXINHA CARNE 140 grs', 0.00, NULL, 1, 'Semiacabado recheio derivado de COXINHA CARNE 140 grs | Planilha: Coxinha', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - COXINHA FRANGO 140 grs' LIMIT 1), 1, 'Recheio para COXINHA FRANGO 140 grs', 0.00, NULL, 1, 'Semiacabado recheio derivado de COXINHA FRANGO 140 grs | Planilha: Coxinha', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - COXINHOCA CARNE SECA 130 grs' LIMIT 1), 1, 'Recheio para COXINHOCA CARNE SECA 130 grs', 0.00, NULL, 1, 'Semiacabado recheio derivado de COXINHOCA CARNE SECA 130 grs | Planilha: Coxinha', NULL),
    ((SELECT id FROM products WHERE name = 'RECHEIO - COXINHOCA FRANGO /REQ 190 grs' LIMIT 1), 1, 'Recheio para COXINHOCA FRANGO /REQ 190 grs', 0.00, NULL, 1, 'Semiacabado recheio derivado de COXINHOCA FRANGO /REQ 190 grs | Planilha: Coxinha', NULL);

-- Itens das fichas tecnicas (quantidades POR UNIDADE produzida)
INSERT INTO produto_template_itens (
    template_id, tipo_item, produto_id, descricao,
    quantidade, unidade_medida, custo_unitario_base, custo_total_base, observacoes
) VALUES
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA CARNE MAND 20 grs' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 25X35 TIMBRADA' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 25X35 TIMBRADA', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA CARNE MAND 20 grs' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA CARNE MAND 20 grs' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA FRANGO MAND 20 grs' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 25X35 TIMBRADA' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 25X35 TIMBRADA', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA FRANGO MAND 20 grs' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA FRANGO MAND 20 grs' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'CROQUETE CARNE SECA 20 GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE SECA' LIMIT 1), 'RECHEIO - CARNE SECA', 0.003000, 'KG', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'CROQUETE CARNE SECA 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 25X35 TIMBRADA' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 25X35 TIMBRADA', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'CROQUETE CARNE SECA 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'CROQUETE CARNE SECA 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 82.898437, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'BOLINHA DE QUEIJO 20 GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = '2 QUEIJOS' LIMIT 1), 'RECHEIO - 2 QUEIJOS', 0.003000, 'KG', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'BOLINHA DE QUEIJO 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 35X45 LISA' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 35X45 LISA', 67.116477, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'BOLINHA DE QUEIJO 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 67.116477, 'ML', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'BOLINHA DE QUEIJO 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 67.116477, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO PRES/QUEIJO 20GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'PRES/QUEIJO' LIMIT 1), 'RECHEIO - PRES/QUEIJO', 0.003000, 'KG', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO PRES/QUEIJO 20GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 25X35 TIMBRADA' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 25X35 TIMBRADA', 66.796875, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO PRES/QUEIJO 20GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 66.796875, 'ML', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO PRES/QUEIJO 20GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 66.796875, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO SALSICHA 20 GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'SALSICHA' LIMIT 1), 'RECHEIO - SALSICHA', 0.006300, 'KG', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO SALSICHA 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 25X35 TIMBRADA' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 25X35 TIMBRADA', 75.068182, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO SALSICHA 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 75.068182, 'ML', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO SALSICHA 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 75.068182, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'QUIBE CARNE 20 GR' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 25X35 TIMBRADA' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 25X35 TIMBRADA', 60.750000, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'QUIBE CARNE 20 GR' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 60.750000, 'ML', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'QUIBE CARNE 20 GR' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 60.750000, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'BOLINHO DE CARNE 20 GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'AGUA' LIMIT 1), 'MASSA - AGUA', 0.004000, 'L', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'BOLINHO DE CARNE 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 25X35 TIMBRADA' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 25X35 TIMBRADA', 67.500000, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'BOLINHO DE CARNE 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 67.500000, 'ML', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'BOLINHO DE CARNE 20 GRS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 67.500000, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'MINI CHURROS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'DOCE DE LEITE' LIMIT 1), 'RECHEIO - DOCE DE LEITE', 0.004000, 'KG', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'MINI CHURROS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'EMBALAGEM 15X25 MINI' LIMIT 1), 'EMPACOTAMENTO - EMBALAGEM 15X25 MINI', 75.000000, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'MINI CHURROS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'ETIQUETA BRANCA' LIMIT 1), 'EMPACOTAMENTO - ETIQUETA BRANCA', 75.000000, 'ML', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'MINI CHURROS' AND t.versao = 1 LIMIT 1), 'consumo_interno', (SELECT id FROM products WHERE name = 'RIBON' LIMIT 1), 'EMPACOTAMENTO - RIBON', 75.000000, 'UN', NULL, NULL, 'Importado de 20g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA MAND FRANGO 70 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.017000, 'KG', NULL, NULL, 'Importado de 70g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RISOLES TRIGO FRANGO 70 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.017000, 'KG', NULL, NULL, 'Importado de 70g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'ENROLADINHO PRES/QUEIJO 70 GR' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'PRES/QUEIJO' LIMIT 1), 'RECHEIO - PRES/QUEIJO', 0.017000, 'KG', NULL, NULL, 'Importado de 70g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'QUIBE CARNE 70 GR' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE' LIMIT 1), 'RECHEIO - CARNE', 0.008000, 'KG', NULL, NULL, 'Importado de 70g'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'QUIBE CARNE 130 GR' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE' LIMIT 1), 'RECHEIO - CARNE', 0.022000, 'KG', NULL, NULL, 'Importado de Quibe'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'QUIBE PROVOLONE 130 GR' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = '3 QUEIJOS' LIMIT 1), 'RECHEIO - 3 QUEIJOS', 0.023000, 'KG', NULL, NULL, 'Importado de Quibe'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'PASTEL DE CARNE' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE' LIMIT 1), 'RECHEIO - CARNE', 0.035000, 'KG', NULL, NULL, 'Importado de Pastel'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'TROUXINHA FRANGO C/ REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.040000, 'KG', NULL, NULL, 'Importado de Pastel'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'TROUXINHA FRANGO C/ REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'Cobertura assados' LIMIT 1), 'RECHEIO - Cobertura assados', 0.010000, 'KG', NULL, NULL, 'Importado de Pastel'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'PÃO DE BATATA REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'Cobertura assados' LIMIT 1), 'RECHEIO - Cobertura assados', 0.035000, 'KG', NULL, NULL, 'Importado de Pastel'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'PÃO DE BATATA CARNE SECA REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE SECA' LIMIT 1), 'RECHEIO - CARNE SECA', 0.025000, 'KG', NULL, NULL, 'Importado de Pastel'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'PÃO DE BATATA CARNE SECA REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'Cobertura assados' LIMIT 1), 'RECHEIO - Cobertura assados', 0.010000, 'KG', NULL, NULL, 'Importado de Pastel'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'PÃO DE BATATA FRANGO/REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.030000, 'KG', NULL, NULL, 'Importado de Pastel'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA CARNE 140 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE' LIMIT 1), 'RECHEIO - CARNE', 0.032000, 'KG', NULL, NULL, 'Importado de Coxinha'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA CARNE 140 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FARINHA ROSCA ESPECIAL' LIMIT 1), 'RECHEIO - FARINHA ROSCA ESPECIAL', 0.003965, 'KG', NULL, NULL, 'Importado de Coxinha'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHA FRANGO 140 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.032000, 'KG', NULL, NULL, 'Importado de Coxinha'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHOCA CARNE SECA 130 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE SECA' LIMIT 1), 'RECHEIO - CARNE SECA', 0.030000, 'KG', NULL, NULL, 'Importado de Coxinha'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHOCA FRANGO /REQ 190 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.040000, 'KG', NULL, NULL, 'Importado de Coxinha'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'COXINHOCA FRANGO /REQ 190 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'Cobertura assados' LIMIT 1), 'RECHEIO - Cobertura assados', 0.010000, 'KG', NULL, NULL, 'Importado de Coxinha'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - CROQUETE CARNE SECA 20 GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE SECA' LIMIT 1), 'RECHEIO - CARNE SECA', 0.003000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de CROQUETE CARNE SECA 20 GRS'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - BOLINHA DE QUEIJO 20 GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = '2 QUEIJOS' LIMIT 1), 'RECHEIO - 2 QUEIJOS', 0.003000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de BOLINHA DE QUEIJO 20 GRS'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - ENROLADINHO PRES/QUEIJO 20GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'PRES/QUEIJO' LIMIT 1), 'RECHEIO - PRES/QUEIJO', 0.003000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de ENROLADINHO PRES/QUEIJO 20GRS'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - ENROLADINHO SALSICHA 20 GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'SALSICHA' LIMIT 1), 'RECHEIO - SALSICHA', 0.006300, 'KG', NULL, NULL, 'Semiacabado recheio derivado de ENROLADINHO SALSICHA 20 GRS'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'MASSA - BOLINHO DE CARNE 20 GRS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'AGUA' LIMIT 1), 'MASSA - AGUA', 0.004000, 'L', NULL, NULL, 'Semiacabado massa derivado de BOLINHO DE CARNE 20 GRS'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - MINI CHURROS' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'DOCE DE LEITE' LIMIT 1), 'RECHEIO - DOCE DE LEITE', 0.004000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de MINI CHURROS'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - COXINHA MAND FRANGO 70 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.017000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de COXINHA MAND FRANGO 70 grs'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - RISOLES TRIGO FRANGO 70 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.017000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de RISOLES TRIGO FRANGO 70 grs'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - ENROLADINHO PRES/QUEIJO 70 GR' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'PRES/QUEIJO' LIMIT 1), 'RECHEIO - PRES/QUEIJO', 0.017000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de ENROLADINHO PRES/QUEIJO 70 GR'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - QUIBE CARNE 70 GR' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE' LIMIT 1), 'RECHEIO - CARNE', 0.008000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de QUIBE CARNE 70 GR'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - QUIBE CARNE 130 GR' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE' LIMIT 1), 'RECHEIO - CARNE', 0.022000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de QUIBE CARNE 130 GR'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - QUIBE PROVOLONE 130 GR' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = '3 QUEIJOS' LIMIT 1), 'RECHEIO - 3 QUEIJOS', 0.023000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de QUIBE PROVOLONE 130 GR'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - PASTEL DE CARNE' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE' LIMIT 1), 'RECHEIO - CARNE', 0.035000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de PASTEL DE CARNE'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - TROUXINHA FRANGO C/ REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.040000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de TROUXINHA FRANGO C/ REQUEIJÃO'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - TROUXINHA FRANGO C/ REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'Cobertura assados' LIMIT 1), 'RECHEIO - Cobertura assados', 0.010000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de TROUXINHA FRANGO C/ REQUEIJÃO'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - PÃO DE BATATA REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'Cobertura assados' LIMIT 1), 'RECHEIO - Cobertura assados', 0.035000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de PÃO DE BATATA REQUEIJÃO'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - PÃO DE BATATA CARNE SECA REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE SECA' LIMIT 1), 'RECHEIO - CARNE SECA', 0.025000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de PÃO DE BATATA CARNE SECA REQUEIJÃO'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - PÃO DE BATATA CARNE SECA REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'Cobertura assados' LIMIT 1), 'RECHEIO - Cobertura assados', 0.010000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de PÃO DE BATATA CARNE SECA REQUEIJÃO'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - PÃO DE BATATA FRANGO/REQUEIJÃO' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.030000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de PÃO DE BATATA FRANGO/REQUEIJÃO'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - COXINHA CARNE 140 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE' LIMIT 1), 'RECHEIO - CARNE', 0.032000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de COXINHA CARNE 140 grs'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - COXINHA CARNE 140 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FARINHA ROSCA ESPECIAL' LIMIT 1), 'RECHEIO - FARINHA ROSCA ESPECIAL', 0.003965, 'KG', NULL, NULL, 'Semiacabado recheio derivado de COXINHA CARNE 140 grs'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - COXINHA FRANGO 140 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.032000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de COXINHA FRANGO 140 grs'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - COXINHOCA CARNE SECA 130 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'CARNE SECA' LIMIT 1), 'RECHEIO - CARNE SECA', 0.030000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de COXINHOCA CARNE SECA 130 grs'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - COXINHOCA FRANGO /REQ 190 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'FRANGO' LIMIT 1), 'RECHEIO - FRANGO', 0.040000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de COXINHOCA FRANGO /REQ 190 grs'),
    ((SELECT t.id FROM produto_templates_producao t JOIN products p ON t.produto_id = p.id WHERE p.name = 'RECHEIO - COXINHOCA FRANGO /REQ 190 grs' AND t.versao = 1 LIMIT 1), 'materia_prima', (SELECT id FROM products WHERE name = 'Cobertura assados' LIMIT 1), 'RECHEIO - Cobertura assados', 0.010000, 'KG', NULL, NULL, 'Semiacabado recheio derivado de COXINHOCA FRANGO /REQ 190 grs');
